### ISSUE TITLE
fails to convert component with unhelpful error

### ISSUE THREAD

**Issue by cdaringe** [poetic/reacterminator#47]
# problem statement

- app crashes

# discusion

```html
<!-- card.html -->
<div class="bill brasky">
  <h4>card title</h4>
  <p>content</p>
</div>
```

```js
$ reacterminator c html/card.html
/usr/local/lib/node_modules/reacterminator/lib/plugins/main/process-each-jsx-snippet.js:74
    const isSvg = $node.get(0).tagName === 'svg';
                              ^

TypeError: Cannot read property 'tagName' of undefined
    at traverse (/usr/local/lib/node_modules/reacterminator/lib/plugins/main/process-each-jsx-snippet.js:74:31)
    at traverse (/usr/local/lib/node_modules/reacterminator/lib/helpers/traverse-cheerio-node.js:2:7)
    at replaceAttrNameForJsx (/usr/local/lib/node_modules/reacterminator/lib/plugins/main/process-each-jsx-snippet.js:72:3)
    at processEachJsxSnippet (/usr/local/lib/node_modules/reacterminator/lib/plugins/main/process-each-jsx-snippet.js:105:3)
    at _.reduce (/usr/local/lib/node_modules/reacterminator/lib/index.js:44:12)
    at /usr/local/lib/node_modules/reacterminator/node_modules/lodash/lodash.js:928:11
    at /usr/local/lib/node_modules/reacterminator/node_modules/lodash/lodash.js:4938:15
    at baseForOwn (/usr/local/lib/node_modules/reacterminator/node_modules/lodash/lodash.js:2988:24)
    at /usr/local/lib/node_modules/reacterminator/node_modules/lodash/lodash.js:4907:18
    at baseReduce (/usr/local/lib/node_modules/reacterminator/node_modules/lodash/lodash.js:925:5)
```

**Comment by Chun-Yang** [comment]
Hey @cdaringe , right now, you have to wrap your divs into body tags.
